defmodule ShopWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shop

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_shop_key",
    signing_salt: "F2uYV3dc",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :shop,
    gzip: not code_reloading?,
    only: ShopWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :shop
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Function plugs 👉 (The author rarely uses function plugs and mostly module plugs)
  plug :check_promo_code3, code: "X-box is amazing"
  
  plug ShopWeb.Router

  # Function plugs ----------------------------- start

  # This code is fine. But it's not the elixir way -- start
  def check_promo_code(%Plug.Conn{} = conn, _opts) do
    # 👉 conn is a struct from Plug.Conn

    # 👉 _opts means it's an optional parameter.
  # It's a keyword list for that

    # Do whatever you want as long as you return the connection
    IO.inspect("Check promo code is working")
    IO.inspect(conn.params)

    promo_code = conn.params["promo"]

    if promo_code == "secret_code" do
      IO.inspect("Promo is true")
      assign(conn, :promo, true)
      # Note, assign returns updated conn. So don't need to return conn again.
      # Second, in elixir the last line is the return one.
    else
      assign(conn, :promo, false)
    end
    #  -- stop
    # conn
  end

  def check_promo_code2(%Plug.Conn{params: %{"promo" => promo}} = conn, _opts) do # Pattern matching
    # 👉 conn is a struct from Plug.Conn

    # 👉 _opts means it's an optional parameter.
  # It's a keyword list for that

    # Do whatever you want as long as you return the connection
    # IO.inspect("Check promo code is working")
    # IO.inspect(conn.params)

    # promo_code = conn.params["promo"]

    if promo == "secret_code" do
      IO.inspect("Promo is true")
      assign(conn, :promo, true)
      # Note, assign returns updated conn. So don't need to return conn again.
      # Second, in elixir the last line is the return one.
    else
      assign(conn, :promo, false)
    end
    #  -- stop
    # conn
  end

  # Third way - More pattern matching
  def check_promo_code3(%Plug.Conn{:params => %{"promo"=> "secret-code"}} = conn, _opts) do # Pattern matching
    assign(conn, :promo, true)
  end

  def check_promo_code3(%Plug.Conn{} = conn, opts) do # Pattern matching
    IO.inspect(opts)
    dbg(opts)
    assign(conn, :promo, false)
  end

  # Function plugs ----------------------------- stop

end
